// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSVokQXOwaFSm5Z7elBNyoKPa6cRFaN94',
    appId: '1:382094643682:web:1a904132514588a52429bb',
    messagingSenderId: '382094643682',
    projectId: 'flutter-anime-verse',
    authDomain: 'flutter-anime-verse.firebaseapp.com',
    storageBucket: 'flutter-anime-verse.firebasestorage.app',
    measurementId: 'G-BBK78TG68V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGph9oauRP1iM7AZcc6i6Nl5sqqzCXgCk',
    appId: '1:382094643682:android:481a6221252153d12429bb',
    messagingSenderId: '382094643682',
    projectId: 'flutter-anime-verse',
    storageBucket: 'flutter-anime-verse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhweMZA8lXsCezNvFkayTXWqwI3VxlWhE',
    appId: '1:382094643682:ios:d7ad219c53abff392429bb',
    messagingSenderId: '382094643682',
    projectId: 'flutter-anime-verse',
    storageBucket: 'flutter-anime-verse.firebasestorage.app',
    iosBundleId: 'com.example.animeVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhweMZA8lXsCezNvFkayTXWqwI3VxlWhE',
    appId: '1:382094643682:ios:d7ad219c53abff392429bb',
    messagingSenderId: '382094643682',
    projectId: 'flutter-anime-verse',
    storageBucket: 'flutter-anime-verse.firebasestorage.app',
    iosBundleId: 'com.example.animeVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSVokQXOwaFSm5Z7elBNyoKPa6cRFaN94',
    appId: '1:382094643682:web:1df5bb12aae14ac02429bb',
    messagingSenderId: '382094643682',
    projectId: 'flutter-anime-verse',
    authDomain: 'flutter-anime-verse.firebaseapp.com',
    storageBucket: 'flutter-anime-verse.firebasestorage.app',
    measurementId: 'G-5LTK7X3EJ6',
  );
}
